version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - Verbalinsurection
  ignore:
  - dependency-name: influxdb
    versions:
    - 5.3.1
  - dependency-name: schedule
    versions:
    - 1.0.0
